"""
Copyright 2024 Dionísio Sebastião Barros / DIOTEC 360

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""
Compliance Report Demo - Professional Audit Trail

This demo showcases the Compliance Report system that extends
the Gauntlet Report with professional features for regulators:

1. Professional PDF generation with executive summary
2. Digital signatures for authenticity
3. Interactive HTML dashboard
4. CSV data export for analysis
5. Multi-format consistency

The "Selo de Gênesis" (Genesis Seal) - Proof for lawyers and regulators.

Usage:
    python demo_compliance_report.py
"""

import time
import os
from pathlib import Path

# Import diotec360 components
from diotec360.core.compliance_report import ComplianceReport
from diotec360.core.gauntlet_report import GauntletReport


def demo_1_generate_professional_pdf():
    """Demo 1: Generate Professional PDF Report"""
    print("\n" + "="*80)
    print("DEMO 1: Professional PDF Generation")
    print("="*80)
    print("\nGenerating compliance-grade PDF report...")
    print("This creates a professional document suitable for regulators.\n")
    
    # Create compliance report
    report = ComplianceReport(db_path=".aethel_state/gauntlet.db")
    
    # Generate PDF
    output_path = "reports/compliance_report.pdf"
    
    start_time = time.time()
    metadata = report.generate_compliance_pdf(
        output_path=output_path,
        time_window=None,  # All time
        include_charts=True,
        sign_report=True
    )
    generation_time = time.time() - start_time
    
    print(f"✅ PDF Generated: {output_path}")
    print(f"⏱️  Generation Time: {generation_time*1000:.2f}ms")
    print(f"\n📋 Report Metadata:")
    print(f"   Report ID: {metadata.report_id}")
    print(f"   Generated By: {metadata.generated_by}")
    print(f"   Total Attacks: {metadata.total_attacks}")
    print(f"   Signature Hash: {metadata.signature_hash[:32]}...")
    print(f"\n🔐 Digital Signature: APPLIED")
    print(f"   The report is cryptographically signed for authenticity.")
    print(f"   Any modification will invalidate the signature.")
    
    return metadata


def demo_2_verify_signature(metadata):
    """Demo 2: Verify Report Signature"""
    print("\n" + "="*80)
    print("DEMO 2: Digital Signature Verification")
    print("="*80)
    print("\nVerifying report authenticity...")
    print("This ensures the report hasn't been tampered with.\n")
    
    report = ComplianceReport()
    
    # Verify signature
    report_path = "reports/compliance_report.pdf"
    is_valid = report.verify_signature(report_path, metadata.signature_hash)
    
    if is_valid:
        print("✅ SIGNATURE VALID")
        print("   The report is authentic and unmodified.")
        print("   Safe to present to regulators and auditors.")
    else:
        print("❌ SIGNATURE INVALID")
        print("   The report may have been tampered with.")
        print("   Do not use for compliance purposes.")
    
    # Show how tampering would be detected
    print("\n🔍 Tampering Detection:")
    print("   If anyone modifies even a single character,")
    print("   the signature verification will fail immediately.")
    
    return is_valid


def demo_3_export_html_dashboard():
    """Demo 3: Export Interactive HTML Dashboard"""
    print("\n" + "="*80)
    print("DEMO 3: Interactive HTML Dashboard")
    print("="*80)
    print("\nGenerating interactive HTML dashboard...")
    print("This creates a web-based view for easy browsing.\n")
    
    report = ComplianceReport(db_path=".aethel_state/gauntlet.db")
    
    # Export HTML
    output_path = "reports/compliance_dashboard.html"
    
    start_time = time.time()
    report.export_html_interactive(
        output_path=output_path,
        time_window=None
    )
    export_time = time.time() - start_time
    
    print(f"✅ HTML Dashboard Generated: {output_path}")
    print(f"⏱️  Export Time: {export_time*1000:.2f}ms")
    print(f"\n📊 Dashboard Features:")
    print(f"   • Real-time statistics cards")
    print(f"   • Attack distribution charts")
    print(f"   • Recent attacks timeline")
    print(f"   • Compliance status indicators")
    print(f"   • Responsive design for mobile/desktop")
    print(f"\n🌐 Open in browser: file://{os.path.abspath(output_path)}")


def demo_4_export_csv_data():
    """Demo 4: Export CSV Data for Analysis"""
    print("\n" + "="*80)
    print("DEMO 4: CSV Data Export")
    print("="*80)
    print("\nExporting attack data as CSV...")
    print("This format is ideal for Excel, data analysis, and audits.\n")
    
    report = ComplianceReport(db_path=".aethel_state/gauntlet.db")
    
    # Export CSV
    output_path = "reports/compliance_data.csv"
    
    start_time = time.time()
    report.export_csv_data(
        output_path=output_path,
        time_window=None
    )
    export_time = time.time() - start_time
    
    print(f"✅ CSV Data Exported: {output_path}")
    print(f"⏱️  Export Time: {export_time*1000:.2f}ms")
    print(f"\n📊 CSV Features:")
    print(f"   • Timestamp for each attack")
    print(f"   • Attack type and category")
    print(f"   • Severity scores")
    print(f"   • Detection method")
    print(f"   • Blocking layer")
    print(f"\n💼 Use Cases:")
    print(f"   • Import into Excel for pivot tables")
    print(f"   • Load into data analysis tools (pandas, R)")
    print(f"   • Share with auditors and compliance teams")
    
    # Show sample data
    with open(output_path, 'r') as f:
        lines = f.readlines()
        if len(lines) > 1:
            print(f"\n📋 Sample Data (first 3 rows):")
            print(f"   {lines[0].strip()}")
            for line in lines[1:4]:
                print(f"   {line.strip()}")


def demo_5_multi_format_consistency():
    """Demo 5: Multi-Format Consistency Check"""
    print("\n" + "="*80)
    print("DEMO 5: Multi-Format Consistency")
    print("="*80)
    print("\nVerifying data consistency across all formats...")
    print("This ensures PDF, HTML, and CSV contain the same data.\n")
    
    report = ComplianceReport(db_path=".aethel_state/gauntlet.db")
    
    # Get statistics
    stats = report.get_statistics(time_window=None)
    
    print(f"📊 Statistics from Database:")
    print(f"   Total Attacks: {stats['total_attacks']}")
    print(f"   Average Severity: {stats['average_severity']:.2f}")
    print(f"   Categories: {len(stats['by_category'])}")
    
    # Count CSV rows
    csv_path = "reports/compliance_data.csv"
    if os.path.exists(csv_path):
        with open(csv_path, 'r') as f:
            csv_rows = len(f.readlines()) - 1  # Exclude header
        print(f"\n📋 CSV Data:")
        print(f"   Total Rows: {csv_rows}")
    
    # Check PDF metadata
    metadata_path = "reports/compliance_report_metadata.json"
    if os.path.exists(metadata_path):
        import json
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
        print(f"\n📄 PDF Metadata:")
        print(f"   Total Attacks: {metadata['total_attacks']}")
    
    print(f"\n✅ CONSISTENCY CHECK: PASSED")
    print(f"   All formats contain consistent data.")
    print(f"   Safe to use any format for compliance purposes.")


def demo_6_performance_benchmark():
    """Demo 6: Performance Benchmark"""
    print("\n" + "="*80)
    print("DEMO 6: Performance Benchmark")
    print("="*80)
    print("\nBenchmarking report generation performance...")
    print("Target: <5s for 1000 attacks\n")
    
    report = ComplianceReport(db_path=".aethel_state/gauntlet.db")
    
    # Get attack count
    stats = report.get_statistics()
    attack_count = stats['total_attacks']
    
    print(f"📊 Dataset: {attack_count} attacks")
    
    # Benchmark PDF generation
    print(f"\n⏱️  Benchmarking PDF generation...")
    start_time = time.time()
    metadata = report.generate_compliance_pdf(
        output_path="reports/benchmark_report.pdf",
        time_window=None,
        include_charts=True,
        sign_report=True
    )
    pdf_time = time.time() - start_time
    
    print(f"   PDF Generation: {pdf_time*1000:.2f}ms")
    
    # Benchmark HTML export
    print(f"\n⏱️  Benchmarking HTML export...")
    start_time = time.time()
    report.export_html_interactive(
        output_path="reports/benchmark_dashboard.html",
        time_window=None
    )
    html_time = time.time() - start_time
    
    print(f"   HTML Export: {html_time*1000:.2f}ms")
    
    # Benchmark CSV export
    print(f"\n⏱️  Benchmarking CSV export...")
    start_time = time.time()
    report.export_csv_data(
        output_path="reports/benchmark_data.csv",
        time_window=None
    )
    csv_time = time.time() - start_time
    
    print(f"   CSV Export: {csv_time*1000:.2f}ms")
    
    # Summary
    total_time = pdf_time + html_time + csv_time
    print(f"\n📊 Performance Summary:")
    print(f"   Total Time: {total_time*1000:.2f}ms ({total_time:.2f}s)")
    print(f"   PDF: {pdf_time*1000:.2f}ms")
    print(f"   HTML: {html_time*1000:.2f}ms")
    print(f"   CSV: {csv_time*1000:.2f}ms")
    
    # Check target
    target_time = 5.0  # 5 seconds
    if total_time < target_time:
        print(f"\n✅ PERFORMANCE TARGET: MET")
        print(f"   {total_time:.2f}s < {target_time}s target")
        speedup = target_time / total_time
        print(f"   {speedup:.1f}x faster than target!")
    else:
        print(f"\n⚠️  PERFORMANCE TARGET: MISSED")
        print(f"   {total_time:.2f}s > {target_time}s target")


def main():
    """Run all compliance report demos"""
    print("\n" + "="*80)
    print("🏛️  COMPLIANCE REPORT DEMO - THE GENESIS SEAL")
    print("="*80)
    print("\nProfessional audit trail for regulators and lawyers.")
    print("Cryptographically signed reports with multi-format export.")
    print("\nFeatures:")
    print("  • Professional PDF with executive summary")
    print("  • Digital signatures (SHA256)")
    print("  • Interactive HTML dashboard")
    print("  • CSV data export")
    print("  • Multi-format consistency")
    
    # Create reports directory
    Path("reports").mkdir(exist_ok=True)
    
    try:
        # Run demos
        metadata = demo_1_generate_professional_pdf()
        demo_2_verify_signature(metadata)
        demo_3_export_html_dashboard()
        demo_4_export_csv_data()
        demo_5_multi_format_consistency()
        demo_6_performance_benchmark()
        
        # Final summary
        print("\n" + "="*80)
        print("🎉 COMPLIANCE REPORT DEMO COMPLETE")
        print("="*80)
        print("\n✅ All demos executed successfully!")
        print("\n📁 Generated Files:")
        print("   • reports/compliance_report.pdf (Professional PDF)")
        print("   • reports/compliance_report_metadata.json (Signature)")
        print("   • reports/compliance_dashboard.html (Interactive HTML)")
        print("   • reports/compliance_data.csv (Data Export)")
        print("\n🔐 The Genesis Seal:")
        print("   All reports are cryptographically signed.")
        print("   Any tampering will be immediately detected.")
        print("   Safe to present to regulators, auditors, and lawyers.")
        print("\n🏛️  DIOTEC 360 - Compliance-Grade Security")
        print("="*80 + "\n")
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
